<a href="https://colab.research.google.com/github/sirishan506-source/google-collab/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Numpy**

1. Numpy stands for numerical python
2. Numpy is a python library function
3. Numpy used for working with arrays
   

In [1]:
import numpy
arr = numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


Numpy usually imported as np

In [2]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


0 D array using numpy

In [5]:
import numpy as np
arr = np.array(42)
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr3 = np.array([[[10,20,30,40,50],[60,70,80,90,100]],[[20,30,40,10,0],[50,20,40,70,80]]])
print(arr)
print(arr1)
print(arr2)
print(arr3)

42
[1 2 3 4 5]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[[ 10  20  30  40  50]
  [ 60  70  80  90 100]]

 [[ 20  30  40  10   0]
  [ 50  20  40  70  80]]]


Numpy provides ndim to display number of dimension

In [2]:
import numpy as np
arr = np.array(49)
arr1 = np.array([1,2,3,4])
arr2 = np.array([[12,13,14,15], [16,17,18,19]])
arr3 = np.array([[[10,20,30,40],[50,60,70,80]],[[20,30,10,20],[30,70,90,50]]])
print(arr.ndim)
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

0
1
2
3


NumPy Array Indexing

In [1]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr[3])

4


Accessing 2D arrays

In [5]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("2nd element in 1st row:",arr[0,1])

2nd element in 1st row: 2


3D **arrays**

print(arr[0, 1, 2]) accesses and prints an element from a 3D NumPy array. Here:

0 = first array,
1 = second row,
2 = third column.

In [7]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])

6


**Numpy array slicing**

Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step]

In [13]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[1:2:3])

[2]


**Data Types in NumPy**

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer

b - boolean

u - unsigned integer

f - float

c - complex float

m - timedelta

M - datetime

O - object

S - string

U - unicode string

V - fixed chunk of memory for other type ( void )

Checking the data type of an array
with atribute called **dtype**



In [16]:
import numpy as np
arr = np.array([1,2,3,4])
arr1 = np.array(['Siri','Raju','Ajay'])
print(arr.dtype)
print(arr1.dtype)

int64
<U4


Creating Arrays With a Defined Data Type

Create an array with data type string:

In [3]:
import numpy as np
arr = np.array([1,2,3,4],dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


Create an array with data type 4 bytes integer:

In [4]:
import numpy as np
arr = np.array([1,2,3,4],dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


Converting Data Type on Existing Arrays with the use of astype atribute

In [5]:
import numpy as np
arr = np.array([1.1,1.2,1.3])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 1 1]
int32


**NumPy Array Copy vs view***

**Copy**:The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

In [6]:
import numpy as np
arr = np.array([1,2,3,4])
x=arr.copy()
arr[0]=42
print(arr)
print(x)

[42  2  3  4]
[1 2 3 4]


**View**:The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [7]:
import numpy as np
arr = np.array([1,2,3,4])
x=arr.view()
arr[0]=42
print(arr)
print(x)


[42  2  3  4]
[42  2  3  4]


**Check if Array Owns its Data**:

As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

Every NumPy array has the attribute *base* that returns None if the array owns the data.

Otherwise, the base  attribute refers to the original object.

In [8]:
import numpy as np
arr=np.array([1,2,3,4])
x=arr.copy()
y=arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4]


**NumPy Array Shape**

NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements

In [9]:
import numpy as np
arr = np.array([[1,2,3,4],[3,5,6,2]])
print(arr.shape)

(2, 4)


Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4:

In [10]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


NumPy Array Reshaping

Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [11]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Convert the following 1-D array with 12 elements into a 3-D array.

The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:

In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)



[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


Flattening the arrays
Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.

In [13]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


**NumPy Array Iterating**

In [15]:
import numpy as np
arr=np.array([1,2,3])
for x in arr:
  print(x)

1
2
3


Iterate down to the scalars:

In [16]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [17]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


# Joining NumPy Arrays
Joining means putting contents of two or more arrays in a single array.

In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

In [18]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


Joining Arrays Using Stack Functions

In [1]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


Stacking Along Rows

NumPy provides a helper function: hstack() to stack along rows.

In [2]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


Stacking Along Columns

NumPy provides a helper function: vstack()  to stack along columns.

In [3]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


Stacking Along Height (depth)

NumPy provides a helper function: dstack() to stack along height, which is the same as depth.

In [4]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
3print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


# NumPy Splitting Array:
Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

**Split Into Arrays**

The return value of the array_split() method is a list containing each of the split as an array.

If you split an array into 3 arrays, you can access them from the result just like any array element:

In [5]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr[0])
print(newarr[1])3*3
print(newarr[2])

[1 2]
[3 4]
[5 6]
